// GENERATED by scripts/sync-chart-glyphs.mjs — do not edit by hand.
//
// Source: kairos-ios @ 15d557658ac5f61e823a3c9e49718edc50ba0d46 (kairos-swift/Assets.xcassets/glyphs)
// Regenerate: npm run sync-glyphs
//
// The provenance line above is load-bearing: re-run the script and diff to
// answer "has this drifted?" (the daoUI tokens.gen.ts header argues the case).
//
// Keys mirror the iOS asset names minus the "glyphs/" prefix:
// "signs/aries", "celestials/north node" (spaces preserved), "rx".
// Values are Metro asset modules (jest's assetFileTransformer stubs them).
// The SVGs use only Skia-supported features (plain paths/strokes/fills —
// verified against the SVG-support list at
// https://shopify.github.io/react-native-skia/docs/images-svg#svg-support).

export const KAIROS_IOS_SOURCE_COMMIT = "15d557658ac5f61e823a3c9e49718edc50ba0d46";

export const GLYPH_COUNT = 66;

export const GLYPH_ASSETS = {
  "celestials/aldebaran": require("../../../../assets/chart-glyphs/celestials/aldebaran.svg"),
  "celestials/altair": require("../../../../assets/chart-glyphs/celestials/altair.svg"),
  "celestials/antares": require("../../../../assets/chart-glyphs/celestials/antares.svg"),
  "celestials/ascendant": require("../../../../assets/chart-glyphs/celestials/ascendant.svg"),
  "celestials/betelgeuse": require("../../../../assets/chart-glyphs/celestials/betelgeuse.svg"),
  "celestials/capella": require("../../../../assets/chart-glyphs/celestials/capella.svg"),
  "celestials/ceres": require("../../../../assets/chart-glyphs/celestials/ceres.svg"),
  "celestials/chiron": require("../../../../assets/chart-glyphs/celestials/chiron.svg"),
  "celestials/descendant": require("../../../../assets/chart-glyphs/celestials/descendant.svg"),
  "celestials/earth": require("../../../../assets/chart-glyphs/celestials/earth.svg"),
  "celestials/eris": require("../../../../assets/chart-glyphs/celestials/eris.svg"),
  "celestials/eros": require("../../../../assets/chart-glyphs/celestials/eros.svg"),
  "celestials/eros-asteroid": require("../../../../assets/chart-glyphs/celestials/eros-asteroid.svg"),
  "celestials/fomalhaut": require("../../../../assets/chart-glyphs/celestials/fomalhaut.svg"),
  "celestials/fortune": require("../../../../assets/chart-glyphs/celestials/fortune.svg"),
  "celestials/imum coeli": require("../../../../assets/chart-glyphs/celestials/imum coeli.svg"),
  "celestials/juno": require("../../../../assets/chart-glyphs/celestials/juno.svg"),
  "celestials/jupiter": require("../../../../assets/chart-glyphs/celestials/jupiter.svg"),
  "celestials/lilith": require("../../../../assets/chart-glyphs/celestials/lilith.svg"),
  "celestials/lot of soul": require("../../../../assets/chart-glyphs/celestials/lot of soul.svg"),
  "celestials/mars": require("../../../../assets/chart-glyphs/celestials/mars.svg"),
  "celestials/mercury": require("../../../../assets/chart-glyphs/celestials/mercury.svg"),
  "celestials/midheaven": require("../../../../assets/chart-glyphs/celestials/midheaven.svg"),
  "celestials/moon": require("../../../../assets/chart-glyphs/celestials/moon.svg"),
  "celestials/neptune": require("../../../../assets/chart-glyphs/celestials/neptune.svg"),
  "celestials/north node": require("../../../../assets/chart-glyphs/celestials/north node.svg"),
  "celestials/pallas": require("../../../../assets/chart-glyphs/celestials/pallas.svg"),
  "celestials/part of fortune": require("../../../../assets/chart-glyphs/celestials/part of fortune.svg"),
  "celestials/pholus": require("../../../../assets/chart-glyphs/celestials/pholus.svg"),
  "celestials/pluto": require("../../../../assets/chart-glyphs/celestials/pluto.svg"),
  "celestials/procyon": require("../../../../assets/chart-glyphs/celestials/procyon.svg"),
  "celestials/regulus": require("../../../../assets/chart-glyphs/celestials/regulus.svg"),
  "celestials/rigel": require("../../../../assets/chart-glyphs/celestials/rigel.svg"),
  "celestials/saturn": require("../../../../assets/chart-glyphs/celestials/saturn.svg"),
  "celestials/sirius": require("../../../../assets/chart-glyphs/celestials/sirius.svg"),
  "celestials/south node": require("../../../../assets/chart-glyphs/celestials/south node.svg"),
  "celestials/spica": require("../../../../assets/chart-glyphs/celestials/spica.svg"),
  "celestials/spirit": require("../../../../assets/chart-glyphs/celestials/spirit.svg"),
  "celestials/star": require("../../../../assets/chart-glyphs/celestials/star.svg"),
  "celestials/sun": require("../../../../assets/chart-glyphs/celestials/sun.svg"),
  "celestials/uranus": require("../../../../assets/chart-glyphs/celestials/uranus.svg"),
  "celestials/vega": require("../../../../assets/chart-glyphs/celestials/vega.svg"),
  "celestials/venus": require("../../../../assets/chart-glyphs/celestials/venus.svg"),
  "celestials/vertex": require("../../../../assets/chart-glyphs/celestials/vertex.svg"),
  "celestials/vesta": require("../../../../assets/chart-glyphs/celestials/vesta.svg"),
  "other/cup": require("../../../../assets/chart-glyphs/other/cup.svg"),
  "other/kairos-logo": require("../../../../assets/chart-glyphs/other/kairos-logo.svg"),
  "other/pentacle": require("../../../../assets/chart-glyphs/other/pentacle.svg"),
  "other/station-direct": require("../../../../assets/chart-glyphs/other/station-direct.svg"),
  "other/station-retrograde": require("../../../../assets/chart-glyphs/other/station-retrograde.svg"),
  "other/sword": require("../../../../assets/chart-glyphs/other/sword.svg"),
  "other/tarot": require("../../../../assets/chart-glyphs/other/tarot.svg"),
  "other/wand": require("../../../../assets/chart-glyphs/other/wand.svg"),
  "rx": require("../../../../assets/chart-glyphs/rx.svg"),
  "signs/aquarius": require("../../../../assets/chart-glyphs/signs/aquarius.svg"),
  "signs/aries": require("../../../../assets/chart-glyphs/signs/aries.svg"),
  "signs/cancer": require("../../../../assets/chart-glyphs/signs/cancer.svg"),
  "signs/capricorn": require("../../../../assets/chart-glyphs/signs/capricorn.svg"),
  "signs/gemini": require("../../../../assets/chart-glyphs/signs/gemini.svg"),
  "signs/leo": require("../../../../assets/chart-glyphs/signs/leo.svg"),
  "signs/libra": require("../../../../assets/chart-glyphs/signs/libra.svg"),
  "signs/pisces": require("../../../../assets/chart-glyphs/signs/pisces.svg"),
  "signs/sagittarius": require("../../../../assets/chart-glyphs/signs/sagittarius.svg"),
  "signs/scorpio": require("../../../../assets/chart-glyphs/signs/scorpio.svg"),
  "signs/taurus": require("../../../../assets/chart-glyphs/signs/taurus.svg"),
  "signs/virgo": require("../../../../assets/chart-glyphs/signs/virgo.svg"),
} as const;

export type GlyphName = keyof typeof GLYPH_ASSETS;
