/**
 * buildConfiguration tests (Task 7) — run the REAL engine fixture
 * (fixtures/engine/sibly-1776.json, generated by kairos-core's
 * dump_chart_response example) through preset → ChartRenderingConfiguration.
 *
 * Semantics mirrored from kairos-ios `PresetConfigurationBuilder.swift`
 * (solo path) — see buildConfiguration.ts for the per-item provenance.
 */

import chart from "../../fixtures/engine/sibly-1776.json";
import classic from "../../fixtures/presets/classic.json";
import starfield from "../../fixtures/presets/starfield.json";
import { parsePreset, type Preset } from "../../schema/preset";
import { buildConfiguration } from "../buildConfiguration";
import type { RingContentType } from "../ChartRenderingConfiguration";
import type { ChartCalculationResponse } from "../engine-types";

const sibly = chart as ChartCalculationResponse;

type PlanetsContent = Extract<RingContentType, { kind: "planets" }>;

function planetsType(cfg: ReturnType<typeof buildConfiguration>): PlanetsContent {
  const ring = cfg.rings.find((r) => r.type.kind === "planets");
  if (!ring) throw new Error("expected a planets ring");
  return ring.type as PlanetsContent;
}

test("classic + sibly builds a solo configuration", () => {
  const cfg = buildConfiguration(sibly, parsePreset(classic));
  expect(cfg.houseCusps).toHaveLength(12);
  expect(cfg.rings.some((r) => r.type.kind === "planets")).toBe(true);
  expect(cfg.orientation).toBe(classic.soloChart.globalSettings.staticOrientationDegree);
});

test("north node appears exactly once, and it is the first in engine order", () => {
  const cfg = buildConfiguration(sibly, parsePreset(classic));
  const planets = planetsType(cfg);
  // Swift's predicate is a three-name set (PresetConfigurationBuilder.swift), not a
  // substring — "south node" must NOT match here.
  const NORTH_NODE_NAMES = new Set(["mean node", "true node", "north node"]);
  const survivors = planets.placements.filter((p) => NORTH_NODE_NAMES.has(p.bodyName.toLowerCase()));
  expect(survivors).toHaveLength(1);
  // WIRE DIVERGENCE (fixture wins): the engine emits `body: "MeanNode"` (no
  // space) — Swift's own three-name predicate never fires on the current wire
  // (iOS-side dead code). Our builder normalizes bodyName to the canonical
  // display name via body_id → enums.gen id, so the placement-side predicate
  // above behaves as Swift intended. The engine-order cross-check therefore
  // matches on the wire's actual spellings and compares the RAW node id
  // (Placement.id passes node.id through so aspect edge endpoints resolve).
  const WIRE_NORTH_NODE_NAMES = new Set([...NORTH_NODE_NAMES, "meannode", "truenode"]);
  const firstInEngineOrder = sibly.celestial.nodes.find((n) =>
    WIRE_NORTH_NODE_NAMES.has(n.body.toLowerCase()),
  );
  expect(firstInEngineOrder).toBeDefined();
  expect(survivors[0].id).toBe(firstInEngineOrder!.id);
  expect(survivors[0].bodyName).toBe("North Node");
});

test("visibility filter drops disabled bodies", () => {
  const p = parsePreset(classic);
  const gated = { ...p, visibility: { enabledBodies: ["sun", "moon"] } };
  const cfg = buildConfiguration(sibly, gated);
  const planets = planetsType(cfg);
  expect(planets.placements.length).toBe(2);
});

test("empty enabledBodies is Swift's .minimal: NOTHING passes, ring dropped", () => {
  // Verified in PresetConfigurationBuilder.swift:144-160 — `ringBodies` is the
  // (possibly empty) set and `contains` gates every placement; an empty set
  // empties the ring and the ring is not appended. The plan's "empty = show
  // everything" guess is NOT Swift's behavior. All seven bundled templates
  // ship non-empty lists, so this only bites hand-built presets.
  const p: Preset = { ...parsePreset(classic), visibility: { enabledBodies: [] } };
  const cfg = buildConfiguration(sibly, p);
  expect(cfg.rings.some((r) => r.type.kind === "planets")).toBe(false);
  // Non-planet rings are unaffected.
  expect(cfg.rings.some((r) => r.type.kind === "zodiacSigns")).toBe(true);
  expect(cfg.rings.some((r) => r.type.kind === "houseNumbers")).toBe(true);
});

test("showFrameDerivedPoints: false drops angles/lots/vertex from that ring", () => {
  // Frame-derived set mirrors CelestialBody.isFrameDerivedPoint (kairos-ios
  // CelestialBody+SubCategories.swift): the four angles + three lots + vertex.
  const p = parsePreset(classic); // classic enables all four angles, no lots/vertex
  const solo = {
    ...p.soloChart,
    rings: p.soloChart.rings.map((r) =>
      r.type === "planets" && r.style.$type.endsWith("planets")
        ? { ...r, style: { ...r.style, showFrameDerivedPoints: false } }
        : r,
    ),
  };
  const cfg = buildConfiguration(sibly, { ...p, soloChart: solo });
  const planets = planetsType(cfg);
  const ids = planets.placements.map((pl) => pl.bodyId);
  expect(ids).not.toContain("ascendant");
  expect(ids).not.toContain("midheaven");
  expect(ids).not.toContain("descendant");
  expect(ids).not.toContain("imumCoeli");
  // classic solo with the angles dropped: 10 planets + rahu + ketu.
  expect(planets.placements).toHaveLength(12);
});

test("unsupported ring types warn and are skipped (starfield fixedStars)", () => {
  const warn = jest.spyOn(console, "warn").mockImplementation(() => {});
  try {
    const cfg = buildConfiguration(sibly, parsePreset(starfield));
    expect(cfg.rings.some((r) => r.type.kind === "zodiacSigns")).toBe(true);
    // fixedStars parses in the schema layer but does not render yet.
    expect(warn).toHaveBeenCalledWith(expect.stringContaining("fixedStars"));
    // zodiac + planets + houses survive; nothing else was appended.
    expect(cfg.rings.map((r) => r.type.kind)).toEqual(["zodiacSigns", "planets", "houseNumbers"]);
  } finally {
    warn.mockRestore();
  }
});

test("aspect edges pass through raw; orientation follows the preset", () => {
  const cfg = buildConfiguration(sibly, parsePreset(classic));
  // Builder does no aspect filtering — AspectConfiguration enabled/orb/type
  // filtering lives in the render overlay (kairos-ios AspectOverlay.swift,
  // AspectFilterResult.evaluate). The config carries the edges verbatim.
  expect(cfg.aspectEdges).toBe(sibly.celestial.edges as unknown as typeof cfg.aspectEdges);
  expect(cfg.aspects).toEqual(parsePreset(classic).aspects);
  // Static orientation is independent of the house-1 cusp.
  expect(cfg.orientation).toBe(classic.soloChart.globalSettings.staticOrientationDegree);
  const rotated = parsePreset(classic);
  rotated.soloChart.globalSettings.staticOrientationDegree = 90;
  expect(buildConfiguration(sibly, rotated).orientation).toBe(90);
  expect(buildConfiguration(sibly, rotated).houseCusps).toEqual(cfg.houseCusps);
});

test("rings preserve slot order (outermost-first, iOS RingGeometry index 0 = outermost)", () => {
  const cfg = buildConfiguration(sibly, parsePreset(classic));
  // classic solo: [zodiac, planets, houses] — zodiac is the outermost band.
  expect(cfg.rings.map((r) => r.type.kind)).toEqual(["zodiacSigns", "planets", "houseNumbers"]);
});

test("placements carry retrograde + glyph asset from enums.gen", () => {
  const cfg = buildConfiguration(sibly, parsePreset(classic));
  const planets = planetsType(cfg);
  const mercury = planets.placements.find((p) => p.bodyId === "mercury");
  const sun = planets.placements.find((p) => p.bodyId === "sun");
  expect(mercury?.isRetrograde).toBe(true); // speed_longitude < 0 in the fixture
  expect(sun?.isRetrograde).toBe(false);
  expect(mercury?.glyphAsset).toBe("mercury");
  // The north node normalizes to the canonical "north node" glyph (iOS
  // CelestialBodyNameMapper.toAssetName does the same for "MeanNode").
  const node = planets.placements.find((p) => p.bodyId === "rahu");
  expect(node?.glyphAsset).toBe("north node");
  expect(node?.bodyName).toBe("North Node");
});
