// GENERATED by scripts/sync-fonts.mjs — do not edit by hand.
//
// Source: daoUI @ ff1cf0b (Sources/DaoUI/Fonts)
// Regenerate: npm run sync-fonts

export const FONT_SOURCE_COMMIT = "ff1cf0b";

/** PostScript names, keyed to the family roles in daoUI's Font+Kairos.swift. */
export const families = {
  "whyte": {
    "book": "ABCWhyteEdu-Book",
    "display": "ABCWhyte-Regular"
  },
  "whyteInk": {
    "book": "ABCWhyteInktrapEdu-Book",
    "display": "ABCWhyteInktrap-Regular"
  },
  "fraktion": {
    "book": "PPFraktionMono-Regular",
    "display": "PPFraktionMono-Regular"
  }
} as const;

/** Pass to useFonts() at the root before rendering. */
export const fontMap: Record<string, number> = {
  "ABCWhyte-Regular": require('@/assets/fonts/ABCWhyte-Regular.otf'),
  "ABCWhyte-RegularItalic": require('@/assets/fonts/ABCWhyte-RegularItalic.otf'),
  "ABCWhyteEdu-Book": require('@/assets/fonts/ABCWhyteEdu-Book.otf'),
  "ABCWhyteInktrap-Regular": require('@/assets/fonts/ABCWhyteInktrap-Regular.otf'),
  "ABCWhyteInktrap-RegularItalic": require('@/assets/fonts/ABCWhyteInktrap-RegularItalic.otf'),
  "ABCWhyteInktrapEdu-Book": require('@/assets/fonts/ABCWhyteInktrapEdu-Book.otf'),
  "PPFraktionMono-Bold": require('@/assets/fonts/PPFraktionMono-Bold.otf'),
  "PPFraktionMono-BoldItalic": require('@/assets/fonts/PPFraktionMono-BoldItalic.otf'),
  "PPFraktionMono-Light": require('@/assets/fonts/PPFraktionMono-Light.otf'),
  "PPFraktionMono-LightItalic": require('@/assets/fonts/PPFraktionMono-LightItalic.otf'),
  "PPFraktionMono-Regular": require('@/assets/fonts/PPFraktionMono-Regular.otf'),
  "PPFraktionMono-RegularItalic": require('@/assets/fonts/PPFraktionMono-RegularItalic.otf'),
};
