// GENERATED by scripts/sync-tokens.mjs — do not edit by hand.
//
// Source: daoUI @ ff1cf0b (tokens.json)
// Regenerate: npm run sync-tokens
//
// The provenance line above is load-bearing. zhouyi carries a src/theme/
// colors.gen.ts whose first line reads "Extracted BY HAND from the daoUI asset
// catalogs" — a .gen filename over content no generator produced, and its
// sibling tokens.ts still cites KairosDesign, which daoUI superseded on
// 2026-07-09. A citation that cannot be followed reads exactly like one that
// can. This file can be followed: re-run the script and diff.

export const DAOUI_SOURCE_COMMIT = "ff1cf0b";

export const ROLE_COUNT = 37;

export const lightColors = {
  "txPrimary": "#191b18ff",
  "txSecondary": "#3d403bbf",
  "txTertiary": "#3d403b80",
  "txBody": "#3d403bf2",
  "txAccent": "#3281fff2",
  "txError": "#e34837f2",
  "txWarning": "#f18736f2",
  "txSuccess": "#436d08f2",
  "txDisabled": "#3d403b38",
  "txButton": "#f8f1e5ff",
  "bgSolidBase": "#f9f2e7ff",
  "bgSolidCard": "#f2eadeff",
  "bgSolidCardSecondary": "#f4ede1ff",
  "bgSolidCardHover": "#ebe3d7ff",
  "bgSolidCardPressed": "#e4dcd1ff",
  "bgSolidButton": "#3d403bff",
  "bgSolidButtonHover": "#282a27ff",
  "bgSolidButtonPressed": "#191b18ff",
  "bgSolidButtonDisabled": "#3d403b26",
  "bgPrimary": "#3d403b14",
  "bgSecondary": "#3d403b08",
  "bgAccent": "#3281ff14",
  "bgWarning": "#f1873614",
  "bgError": "#e3483714",
  "bgHover": "#3d403b1f",
  "bgPressed": "#3d403b26",
  "bdBase": "#2c2721cc",
  "bdPrimary": "#3d403b26",
  "bdSecondary": "#3d403b14",
  "bdCard": "#91836e59",
  "bdAccent": "#3281ff59",
  "bdHover": "#3d403b2b",
  "bdPressed": "#3d403b2e",
  "icPrimary": "#191b18e6",
  "icSecondary": "#3d403b99",
  "icTertiary": "#3d403b66",
  "icAccent": "#3281ffe6"
} as const;

export const darkColors = {
  "txPrimary": "#fefffff2",
  "txSecondary": "#f3f6f8b3",
  "txTertiary": "#f3f6f880",
  "txBody": "#f3f6f8f2",
  "txAccent": "#3281fff2",
  "txError": "#ff4b4bf2",
  "txWarning": "#f18736f2",
  "txSuccess": "#9bc874f2",
  "txDisabled": "#f3f6f833",
  "txButton": "#3d403bff",
  "bgSolidBase": "#1a1714ff",
  "bgSolidCard": "#2c2721ff",
  "bgSolidCardSecondary": "#36312bff",
  "bgSolidCardHover": "#342f2aff",
  "bgSolidCardPressed": "#3c3832ff",
  "bgSolidButton": "#f2e9d9ff",
  "bgSolidButtonHover": "#eee2ceff",
  "bgSolidButtonPressed": "#e4dccdff",
  "bgSolidButtonDisabled": "#f2e9d926",
  "bgPrimary": "#f3f6f814",
  "bgSecondary": "#f3f6f80d",
  "bgAccent": "#3281ff14",
  "bgWarning": "#f1873614",
  "bgError": "#ff4b4b14",
  "bgHover": "#f3f6f81f",
  "bgPressed": "#f3f6f826",
  "bdBase": "#000000ff",
  "bdPrimary": "#f3f6f826",
  "bdSecondary": "#f3f6f814",
  "bdCard": "#e6d3b226",
  "bdAccent": "#3281ff59",
  "bdHover": "#f3f6f82b",
  "bdPressed": "#f3f6f82e",
  "icPrimary": "#f3f6f8e6",
  "icSecondary": "#f3f6f899",
  "icTertiary": "#f3f6f866",
  "icAccent": "#3281ffe6"
} as const;

export type ColorRole = keyof typeof lightColors;
