// GENERATED by scripts/sync-type.mjs — do not edit by hand.
//
// Source: daoUI @ ee31269 (type.json — the 2026-08-05 type canon:
// the scale ramp is law; the semantic ramp is deleted upstream and a law test
// keeps it dead)
// Regenerate: npm run sync-type
//
// The provenance line is load-bearing: re-run the script and diff to answer
// "has this drifted?".

export const TYPE_SOURCE_COMMIT = "ee31269";

export const TYPE_STEP_COUNT = 12;

export const typeRamp = {
  whyteXl: { fontSize: 33, lineHeight: 52, fontFamily: "ABCWhyteInktrap-Regular" },
  whyteLg: { fontSize: 26, lineHeight: 42, fontFamily: "ABCWhyteInktrap-Regular" },
  whyteMd: { fontSize: 20, lineHeight: 32, fontFamily: "ABCWhyteInktrap-Regular" },
  whyteSm: { fontSize: 16, lineHeight: 24, fontFamily: "ABCWhyteEdu-Book" },
  whyteXs: { fontSize: 13, lineHeight: 16, fontFamily: "ABCWhyteEdu-Book" },
  whyteXxs: { fontSize: 9, lineHeight: 12, fontFamily: "ABCWhyteEdu-Book" },
  fraktionXl: { fontSize: 33, lineHeight: 52, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.66 },
  fraktionLg: { fontSize: 26, lineHeight: 42, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.52 },
  fraktionMd: { fontSize: 20, lineHeight: 32, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.4 },
  fraktionSm: { fontSize: 16, lineHeight: 24, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.32 },
  fraktionXs: { fontSize: 13, lineHeight: 16, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.26 },
  fraktionXxs: { fontSize: 9, lineHeight: 12, fontFamily: "PPFraktionMono-Regular", letterSpacing: 0.18 },
} as const;

export type TypeStep = keyof typeof typeRamp;
