import { isCurrentSession, type SessionSnapshot } from '@/auth/session';
import { archiveRequest } from '../api';
import { addTransferredChart, previewConversions, retrieveConvertedDestinations, CONVERSION_PROFILE, type ConversionPreview } from '../conversion';
import type { ArchivedChart } from '../types';
import { createChartLibraryStore } from '../../library/store';
import { testDatabase } from '../../library/test-support/sqlite';
import { DEFAULT_SETTINGS } from '../../settings/chartSettings';
jest.mock('expo-sqlite', () => ({ openDatabaseAsync: jest.fn() }));
jest.mock('@react-native-async-storage/async-storage', () => ({ getItem: jest.fn() }));
jest.mock('@/auth/session', () => ({ isCurrentSession: jest.fn() }));
jest.mock('../api', () => ({ archiveRequest: jest.fn() }));
jest.mock('expo-crypto', () => ({ CryptoDigestAlgorithm: { SHA256: 'SHA256' }, digestStringAsync: async (_: string, value: string) => jest.requireActual<typeof import('node:crypto')>('node:crypto').createHash('sha256').update(value).digest('hex') }));
const session = { account: { did: 'did:plc:a', handle: 'test' }, token: 'token', generation: 1 } as SessionSnapshot;
const draft = { name: 'Original', datetime: '2000-01-01T12:00:00.000Z', settings: DEFAULT_SETTINGS };
const preview: ConversionPreview = { transferId: 'source', snapshotId: 'snapshot', profileVersion: CONVERSION_PROFILE, state: 'needs_review', reasons: ['confirm_ordinary_chart'], chart: draft, destinationChartId: null, record: null };
const record = { id: 'destination', revision: 1, updatedAt: '2026-10-02T00:00:00Z', chart: draft };
let db: ReturnType<typeof testDatabase>;
beforeEach(() => { jest.clearAllMocks(); db = testDatabase(); jest.mocked(isCurrentSession).mockReturnValue(true); });
afterEach(() => db.close());
const signal = () => new AbortController().signal;
it('requires review, retains stable retry IDs and downloads without enabling sync or advancing its cursor', async () => {
  const library = await createChartLibraryStore(db.db);
  const operations: string[] = [];
  jest.mocked(archiveRequest).mockImplementation(async (_path, _session, _signal, init) => {
    const request = JSON.parse(init!.body as string); operations.push(request.operationId);
    if (operations.length === 1) throw new Error('Lost acknowledgement');
    return { receipt: { ...request, transferId: preview.transferId, status: 'added', destinationChartId: record.id }, record };
  });
  await expect(addTransferredChart(preview, false, session, signal(), library)).rejects.toThrow('Review');
  expect(archiveRequest).not.toHaveBeenCalled();
  await expect(addTransferredChart(preview, true, session, signal(), library)).rejects.toThrow('Lost');
  await addTransferredChart(preview, true, session, signal(), library);
  expect(operations[0]).toEqual(operations[1]);
  expect((await library.load(session.account.did, DEFAULT_SETTINGS)).saved).toHaveLength(1);
  expect(await library.pending(session.account.did)).toEqual([]);
  expect(await library.syncState(session.account.did)).toMatchObject({ enabled: false, cursor: 0 });
});
it('preserves local edits and deletions, separates independent identical charts and rolls back a switched account', async () => {
  const library = await createChartLibraryStore(db.db), did = session.account.did;
  await library.acceptTransferredChart(did, record, () => true);
  await library.acceptTransferredChart(did, { ...record, id: 'independent' }, () => true);
  await library.saveChart(did, { ...draft, name: 'Edited' }, record.id);
  await library.acceptTransferredChart(did, { ...record, revision: 2 }, () => true);
  expect((await library.load(did, DEFAULT_SETTINGS)).saved.find(c => c.id === record.id)?.name).toBe('Edited');
  await library.deleteChart(did, record.id);
  await library.acceptTransferredChart(did, { ...record, revision: 3 }, () => true);
  expect((await library.load(did, DEFAULT_SETTINGS)).saved.map(c => c.id)).toEqual(['independent']);
  let checks = 0;
  await expect(library.acceptTransferredChart(did, { ...record, id: 'rollback' }, () => ++checks === 1)).rejects.toThrow('Account changed');
  expect((await library.load(did, DEFAULT_SETTINGS)).saved).toHaveLength(1);
  expect((await library.load('did:plc:b', DEFAULT_SETTINGS)).saved).toEqual([]);
});
it('recovers existing destinations after acknowledgement loss with ordinary sync paused', async () => {
  const library = await createChartLibraryStore(db.db);
  const source = { ...preview, name: draft.name, destinationChartId: record.id } as unknown as ArchivedChart;
  jest.mocked(archiveRequest).mockImplementation(async path => path === '/capabilities' ? { conversionProfile: CONVERSION_PROFILE } : { previews: [{ ...preview, state: 'already_added', chart: null, destinationChartId: record.id, record }] });
  await retrieveConvertedDestinations([source], session, signal(), library);
  expect((await library.load(session.account.did, DEFAULT_SETTINGS)).saved[0].id).toBe(record.id);
  expect((await library.syncState(session.account.did)).enabled).toBe(false);
  expect(jest.mocked(archiveRequest).mock.calls.every(([path]) => path !== '/conversions')).toBe(true);
});
it('rejects mismatched assessments, unsupported additions and stale account acknowledgements', async () => {
  const library = await createChartLibraryStore(db.db);
  const source = { ...preview, name: draft.name } as unknown as ArchivedChart;
  jest.mocked(archiveRequest).mockImplementation(async path => path === '/capabilities' ? { conversionProfile: CONVERSION_PROFILE } : { previews: [{ ...preview, transferId: 'wrong' }] });
  await expect(previewConversions([source], session, signal())).rejects.toThrow('Invalid compatibility');
  await expect(addTransferredChart({ ...preview, state: 'unsupported' }, true, session, signal(), library)).rejects.toThrow('Review');
  jest.mocked(archiveRequest).mockImplementation(async (_path, _session, _signal, init) => ({ receipt: { ...JSON.parse(init!.body as string), transferId: preview.transferId, status: 'added', destinationChartId: record.id }, record }));
  jest.mocked(isCurrentSession).mockReturnValue(false);
  await expect(addTransferredChart(preview, true, session, signal(), library)).rejects.toThrow('Account changed');
  expect((await library.load(session.account.did, DEFAULT_SETTINGS)).saved).toEqual([]);
});
