#!/usr/bin/env node
// Copies daoUI's font binaries into this repo and generates the registration map.
//
// daoUI ships its three families inside the Swift package bundle, where a React
// Native app cannot reach them. zhouyi solved this by copying the .otf files in
// by hand — which works, and leaves no way to answer "has this drifted?".
// Generated-and-committed, like sync-tokens.mjs, for the same reason: CI builds
// this repo alone and ../daoUI is not present there.
//
// Run: npm run sync-fonts

import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DAOUI = process.env.DAOUI_PATH ?? join(HERE, '..', '..', 'daoUI');
const SRC = join(DAOUI, 'Sources', 'DaoUI', 'Fonts');
const DEST = join(HERE, '..', 'assets', 'fonts');
const OUT = join(HERE, '..', 'src', 'theme', 'fonts.gen.ts');

// The ramp in daoUI's Font+Kairos.swift: each family has a book weight used
// xs–lg and a display cut used at xl.
const FAMILIES = {
  whyte: { book: 'ABCWhyteEdu-Book', display: 'ABCWhyte-Regular' },
  whyteInk: { book: 'ABCWhyteInktrapEdu-Book', display: 'ABCWhyteInktrap-Regular' },
  fraktion: { book: 'PPFraktionMono-Regular', display: 'PPFraktionMono-Regular' },
};

function die(message) {
  console.error(`sync-fonts: ${message}`);
  process.exit(1);
}

if (!existsSync(SRC)) die(`no fonts at ${SRC}. Clone daoUI beside this repo, or set DAOUI_PATH.`);

const faces = readdirSync(SRC).filter((f) => f.endsWith('.otf')).sort();
if (faces.length === 0) die(`${SRC} contains no .otf files.`);

for (const family of Object.values(FAMILIES)) {
  for (const name of [family.book, family.display]) {
    if (!faces.includes(`${name}.otf`)) die(`the ramp names "${name}" but daoUI does not ship it.`);
  }
}

let sourceCommit = 'unknown';
try {
  sourceCommit = execFileSync('git', ['-C', DAOUI, 'rev-parse', '--short', 'HEAD'], {
    encoding: 'utf8',
  }).trim();
} catch {
  console.warn('sync-fonts: could not read daoUI HEAD; stamping "unknown"');
}

mkdirSync(DEST, { recursive: true });

// Replace, not merge: a face daoUI has since renamed or dropped must not
// survive as a stale committed binary with no git diff signal. Scoped to
// .otf so this never touches anything else that might live in DEST.
const stale = readdirSync(DEST).filter((f) => f.endsWith('.otf') && !faces.includes(f));
for (const face of stale) {
  unlinkSync(join(DEST, face));
  console.log(`sync-fonts: pruned stale ${face}`);
}

for (const face of faces) copyFileSync(join(SRC, face), join(DEST, face));

const entries = faces
  .map((face) => `  ${JSON.stringify(face.replace(/\.otf$/, ''))}: require('@/assets/fonts/${face}'),`)
  .join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/sync-fonts.mjs — do not edit by hand.
//
// Source: daoUI @ ${sourceCommit} (Sources/DaoUI/Fonts)
// Regenerate: npm run sync-fonts

export const FONT_SOURCE_COMMIT = ${JSON.stringify(sourceCommit)};

/** PostScript names, keyed to the family roles in daoUI's Font+Kairos.swift. */
export const families = ${JSON.stringify(FAMILIES, null, 2)} as const;

/** Pass to useFonts() at the root before rendering. */
export const fontMap: Record<string, number> = {
${entries}
};
`,
);

console.log(`sync-fonts: copied ${faces.length} faces from daoUI @ ${sourceCommit}`);
