#!/usr/bin/env node
// Generates src/theme/type.gen.ts from daoUI's type canon.
//
// Since the 2026-08-05 type canon (daoUI PR #14), type.json sits beside
// tokens.json as a canonical file: the scale ramp is the law, and the semantic
// ramp (display/title/heading/…) is deleted upstream with a law test keeping
// it dead. The family carries the voice and the step carries the size — the
// whyte face switch (Inktrap -> Edu Book at md->sm) lives INSIDE the style,
// not at the call site.
//
// Generated-and-committed like its sibling scripts, for the same reason: CI
// builds this repo alone and ../daoUI does not exist there.
//
// Run: npm run sync-type

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DAOUI = process.env.DAOUI_PATH ?? join(HERE, '..', '..', 'daoUI');
const OUT = join(HERE, '..', 'src', 'theme', 'type.gen.ts');

function die(message) {
  console.error(`sync-type: ${message}`);
  process.exit(1);
}

const typePath = join(DAOUI, 'type.json');
if (!existsSync(typePath)) {
  die(`no type.json at ${typePath}. Clone daoUI beside this repo (or set DAOUI_PATH) — and make sure it is past the 2026-08-05 type canon.`);
}

const { styles } = JSON.parse(readFileSync(typePath, 'utf8'));
const entries = Object.entries(styles);
if (entries.length === 0) die(`${typePath} carries no styles.`);

let sourceCommit = 'unknown';
try {
  sourceCommit = execFileSync('git', ['-C', DAOUI, 'rev-parse', '--short', 'HEAD'], {
    encoding: 'utf8',
  }).trim();
} catch {
  console.warn('sync-type: could not read daoUI HEAD; stamping "unknown"');
}

/** `whyte/xl` -> `whyteXl`, `fraktion/xxs` -> `fraktionXxs`. Code keys mirror
 * Figma style names flat, extending the whyteXs precedent. */
function key(name) {
  const [family, step] = name.split('/');
  if (!family || !step) die(`style "${name}" is not family/step. The canon shape changed; fix the generator.`);
  return family + step.charAt(0).toUpperCase() + step.slice(1);
}

/** daoUI carries tracking as a percent of size; RN's letterSpacing is points. */
function letterSpacing(size, trackingPercent) {
  return Math.round(size * trackingPercent) / 100;
}

const seen = {};
const lines = [];
for (const [name, spec] of entries) {
  const k = key(name);
  if (seen[k]) die(`collision: "${name}" and "${seen[k]}" both key to "${k}".`);
  seen[k] = name;

  const fields = [
    `fontSize: ${spec.size}`,
    `lineHeight: ${spec.lineHeight}`,
    `fontFamily: ${JSON.stringify(spec.font)}`,
  ];
  if (spec.trackingPercent !== undefined) {
    fields.push(`letterSpacing: ${letterSpacing(spec.size, spec.trackingPercent)}`);
  }
  lines.push(`  ${k}: { ${fields.join(', ')} },`);
}

const body = `// GENERATED by scripts/sync-type.mjs — do not edit by hand.
//
// Source: daoUI @ ${sourceCommit} (type.json — the 2026-08-05 type canon:
// the scale ramp is law; the semantic ramp is deleted upstream and a law test
// keeps it dead)
// Regenerate: npm run sync-type
//
// The provenance line is load-bearing: re-run the script and diff to answer
// "has this drifted?".

export const TYPE_SOURCE_COMMIT = ${JSON.stringify(sourceCommit)};

export const TYPE_STEP_COUNT = ${entries.length};

export const typeRamp = {
${lines.join('\n')}
} as const;

export type TypeStep = keyof typeof typeRamp;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`sync-type: wrote ${entries.length} steps from daoUI @ ${sourceCommit}`);
